### ISSUE TITLE
home-assistant

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#1]
Hi Magnus! Do you use your project with home-assistant? Can you maybe share some more details about the setup? I understand that this is not an "issue" about inetbox2mqtt but would be very happy to get a better understanding what is possible (and maybe also what not) from your experience. I already know about Daniel's setup (at least from his slides and recent webinar) but that was already very much advanced for me. ;)
Wishing you all a nice weekend! :)

**Comment by mc0110** [comment]
Hi, I don't understand exactly what you want to know. Is it about the realisation of the control of the TRUMA from HA, e.g. what the frontend looks like? Or is it about the functionalities as a whole?

**Comment by mc0110** [comment]
Would you be so kind to send me the link for the webinar, mentioned above

**Comment by mc0110** [comment]
If I'm right, you are interesting in the whole smart motorhome-concept? Right?

**Comment by mc0110** [comment]
I have already taken your suggestion on board. You can now find an example of my current frontend in the docs. 

Yes, indeed, the "whole setup" is too much not for the issue pages. But I will also take your suggestion and make a separate repository for this item. But give me a little time, pls.

**Comment by mc0110** [comment]
Is your ESP32 now in use?

**Comment by mc0110** [comment]
Yes, you should be able to c/p it, because the entity-names should be the same. 

`type: vertical-stack
cards:
  - type: entity
    entity: sensor.truma_clock
    name: TRUMA Zeit
  - show_name: false
    show_icon: true
    show_state: true
    type: glance
    entities:
      - entity: sensor.truma_heating_mode
        name: Lüfter
        icon: mdi:fan-auto
      - entity: sensor.truma_energy_mix
        name: Energie
        icon: mdi:fuel-cell
      - entity: sensor.truma_el_power_level
        name: El-Mode
        icon: mdi:lightning-bolt-outline
    columns: 3
  - show_name: false
    show_icon: true
    show_state: true
    type: glance
    entities:
      - entity: sensor.truma_operating_status
        name: Mode
        icon: mdi:state-machine
      - entity: sensor.truma_error_code
        icon: mdi:head-question
      - entity: binary_sensor.truma_alive
        name: Lin-Kom
    columns: 3
  - type: horizontal-stack
    cards:
      - type: entity
        entity: sensor.truma_current_temp_water
        name: Wasser
      - type: entity
        entity: sensor.truma_target_temp_water
        name: Ziel
    title: Temperaturen
  - type: horizontal-stack
    cards:
      - type: entity
        entity: sensor.truma_current_temp_room
        name: Raum
      - type: entity
        entity: sensor.truma_target_temp_room
        name: Ziel
  - type: entities
    entities:
      - entity: select.truma_set_roomtemp
        name: Raumtemperatur
      - entity: select.truma_set_heating_mode
        name: Lüfter-Mode (off, eco, high)
    title: Einstellung
  - type: entities
    entities:
      - entity: select.truma_set_energy_mix
        name: Energie_Mix (gas, electricity, mix)
      - entity: select.truma_set_el_power_level
        name: EL_Power (0, 900,1800)
  - type: entities
    entities:
      - entity: select.truma_set_warmwater
        name: Warmwasser (0, 40, 60, 200)
`

I think it's a great idea to put it on the site as well. But for me it's more of a side note that doesn't belong on the main page of the project. There are a lot of people who realise it in other systems. We have planned to publish other examples there as well. Okay for you?

**Comment by mc0110** [comment]
I am already looking forward to the discussions with you on the "whole setup".

**Comment by mc0110** [comment]
All of life is a compromise! Cheers!

**Comment by mc0110** [comment]
Which functionality would you lose?

**Comment by mc0110** [comment]
This is unfortunately true and a stupid behaviour of the HA - especially with select-entities.
You only see sensor-entities in the upper fields (up to "Settings") and they are constantly updated. 
The lower select-entities, below "Einstellungen" on the other hand can be changed in Lovelance and then HA publishes the command once via the MQTT server. 
So - imported to know - the value  has to be changed for re-sending something to the MQTT. 

I will therefore replace the selections with buttons in an "improved" version of the frontend, which will then trigger the MQTT commands in an automation. But that's fine-tuning, once the inetbox has had its teething troubles removed. In particular, I can implement such things without having to sit in the vehicle.
