### ISSUE TITLE
Truma LevelControl (gas level) support?

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#10]
Hi Magnus!

I have a Truma LevelControl attached to my gas bottle and can view the gas level in the **Truma app** (only when the iNet box is connected, which communicates with the LevelControl via Bluetooth) or in the **LevelControl app** (also from Truma) that communicates with the LevelControl also via Bluetooth, but directly from the mobile device, i.e. without the need of the iNet box.

Since the ESP32 is fitted with Bluetooth, too, I wonder what it takes to add support for the LevelControl. 

Do you maybe have some advice how I could sniff the (Bluetooth) data traffic between the LevelControl and a) my mobile, or b) my ESP32? Or is there something else to be done to find out more about it?

Thanks for sharing your thoughts!

**Comment by wolfganghuse** [comment]
On iOS i use nRF Connect... for Android there should be similiar apps. You should try to scan with LevelControl in range to get first details like MAC, Manufacturer Data and after connecting to the device the advertised Services.

**Comment by wolfganghuse** [comment]
the uuids are not secrets, on the contrary, they describe the various services offered, please provide also them...

FYI:
R: Read Value
W: Write Value
N: Notification
I: Indication

**Comment by wolfganghuse** [comment]
ok, looks good... as you can see the 128bit UUIDs are quite generic chosen for the advertised services... keen to see the data behind the services... please try to read for every uuid.

P.S.: I am tomorrow on our camper yard, seems i will try to scan surroundings for LevelControls ;-)

**Comment by wolfganghuse** [comment]
Would be good to have a screenshot from the official app at the same time. I don’t know what kind of data is provided? Is it just level or maybe some more data? What can be configured in the app?
There are writable services… do the value change if you change something within the app?

**Comment by wolfganghuse** [comment]
I mean official Truma app

**Comment by wolfganghuse** [comment]
we will also need some more data points to see when, what data changes... Static view is quite complicated for reverse engineering

**Comment by wolfganghuse** [comment]
Yes, makes sense… if you cross check with Mopeka implementation there may be much calculation needed to do. Not sure how successful we will be

**Comment by andypnz** [comment]
Hi. Just wondering if anyone has any update on LevelControl? That would be a nice addition to this project - to receive an alarm on low gas level with no Truma App, etc required......
