### ISSUE TITLE
Caveat about Truma update?

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#11]
@mc0110 
I opened the Truma app the first time after a longer while not using it and received a message about an available update. It reads (in German):

> INET BOX UPDATE VERFÜGBAR
> Bitte laden Sie das Update innerhalb der nächsten 30 Tage auf alle Endgeräte sowie Ihre Truma iNet Box, um die Funktionen Ihres Systems auch weiterhin sicherzustellen.
> OK

It reminds of other IoT gadgets that receive vendors' updates that are not always to the best of the customers. Regarding the **inetbox2mqtt project**, I wonder if the vendor could change the workings of the Truma communication protocol (incl. encryption, maybe?) that could render this nice project useless.

Do you or anybody else knowledgeable of the protocol etc. have a clue if this could happen?

I assume that as long as no iNet box is connected and used, no undesired update can happen. Maybe people who do use the iNet box, might face problems with remote control (sending/receiving SMS), if not updating the software/firmware.

Thanks for sharing your thoughts!

**Comment by mc0110** [comment]
There is no relationship between inetbox-app-updates and the inetbox-simulation
