### ISSUE TITLE
Function of dtoggle_led in tools.py ???

### ISSUE THREAD

**Issue by Harry-58** [mc0110/inetbox2mqtt#14]
What should the function "dtoggle_led" in tools.py do?
Two times NOT results in YES, which does not change the state of the LED!

**Comment by mc0110** [comment]
This is exactly, what we want. So the state won't changed but the led flickers. Pls see the [README](https://github.com/mc0110/inetbox2mqtt#esp32-gpios-and-leds---debugging-will-be-easier) for details.

**Comment by Harry-58** [comment]
I think that is wrong.
The two lines are without delay directly behind each other.
The time interval is only nano/microseconds.
There is absolutely nothing to see on the LED!
I have tested this in a loop.

**Comment by mc0110** [comment]
Sorry, Harry - the code is running and I see the led flickering. I agree, that I wasn't sure, that it will be function without delay, but it do!

**Comment by Harry-58** [comment]
I think the flickering you see comes from the toggle_led in _send_answer.

**Comment by mc0110** [comment]
If you think so - without INIT on CPplus the port doesn't send one byte, but the led is flickering. I don't understand, what the problem is because it is only a debugging feature.
