### ISSUE TITLE
Operating status

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#15]
Hi Magnus!

What is the operating_status about? E.g. "start/cool down"? I see this in MQTT but don't know its meaning. I have not powered the gas on and therefore am puzzled a bit about the term "cool down". 😉

**Comment by mc0110** [comment]
Great!
Let me explain briefly. If the heating is switched off, then no buffer is transmitted that contains the operating status. Only when you switch on the water or heater will the status be communicated. This can contain levels 1-7. When the heating is switched off, the status continues to be communicated during the after-running time, but the status level is reduced from 7 to 1. Then the CPplus stops the transmission. So the last level = 1 always remains in the status. This is my observation.
