### ISSUE TITLE
Keeping inetbox2mqtt on the ESP32 up to date via OTA?

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#17]
Hi Magnus,

This isn't really an issue but rather a question about "best practice": What can you recommend about keeping my ESP32 up to date with your development without necessarily removing it from my campervan, bringing it home, attaching it to my laptop/PC, etc.? Is it possible to update it via OTA maybe? If yes, would you mind providing some brief hints how to? If you want, I could then add that info also in the README of my fork (a bit behind now, but I will catch up) and create a PR. Thanks for your kind consideration!

**Comment by snipah** [comment]
ESPhome is a great piece of kit. Would be great, if this could be ported over, as ESPhome brings all the nice features you are asking for, like an online-update for example :)

**Comment by snipah** [comment]
ESPhome is just the basis, which can be extended...

Is your van accessible over the internet or only via direct WLAN-access in the car?

**Comment by mc0110** [comment]
Hi snipah,
thank you for the enthusiastic discussion. 

I already have years of experience with ESPHOME devices and more than 20 of them in permanent operation. I have been looking into implementing inetbox2mqtt as a custom component for quite some time. But the docs are not detailed enough and the developers themselves mention that the API is unstable. So for a completed solution it made more sense for me to concentrate on the implementation of the LIN communication. 

Please let me make it clear again. A 1-1 porting of Daniel's great software will not work on an ESP32, nor will it work on a pico. I have had to implement all communication with the CPplus differently to get the software to respond quickly enough. 

On the OTA topic, I would like to refer to the discussion on "web-frontend" by 7wells. There I give an outlook on already testable parts ;-)

**Comment by mc0110** [comment]
With the implementation of OTA support, I think we can close the discussion here.
