### ISSUE TITLE
Message "INFO:mqtt_async:Connecting to..." repeating in Thonny Shell

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#2]
Hi Magnus, why is this one line repeating in the Thonny Shell? I hope it does not mean that the connection does not work and is thus tried again and again. How/where can I check this?

FYI, the IP is the one of my RPi4 that runs the mqtt service, which I entered when setting up your tool on my ESP32 for the first time. BTW, I redacted the id below.
```
INFO:mqtt_async:connecting wifi
lin-loop is running
INFO:mqtt_async:Connecting to ('192.168.178.55', 1883) id=b'xxxxxxxxxxxx' clean=0
INFO:mqtt_async:Connecting to ('192.168.178.55', 1883) id=b'xxxxxxxxxxxx' clean=0
INFO:mqtt_async:Connecting to ('192.168.178.55', 1883) id=b'xxxxxxxxxxxx' clean=0
INFO:mqtt_async:Connecting to ('192.168.178.55', 1883) id=b'xxxxxxxxxxxx' clean=0
INFO:mqtt_async:Connecting to ('192.168.178.55', 1883) id=b'xxxxxxxxxxxx' clean=0
```

Right now, the ESP32 is plugged into my laptop (for power and to tinker a bit with it) and is connected via Wifi to both my local network at home and to my RPi4 in my motorhome. The RPi4 is connected (via UART-LIN board with Daniel's tool) to my CP+/Truma. On the long term, I would like to exchange the RPI4 by the ESP32. Whether I will have to keep the RPI4 in the motorhome, I do not yet fully understand.

As my ESP32 is not yet connected to my Truma/motorcar, I do not expect more info and cannot yet provide more feedback. Hopefully, on Sunday or beginning of the coming week.

**Comment by mc0110** [comment]
The line is repeated because the ESP32 cannot establish a connection to the MQTT broker. Something is wrong. Please check the credentials again and try to reboot the chip again. I could observe this in the past from time to time. I suspect it is the Python kernel. Something in the WiFi stack is not clearly initialised.
