### ISSUE TITLE
Connection not working! 

### ISSUE THREAD

**Issue by snipah** [mc0110/inetbox2mqtt#20]
Check for credentials.dat
credentials.dat file exists -> pass the ask for credentials
Found ESP32 Board, using UART2 for LIN on GPIO 16(rx), 17(tx)
main-loop is running
INFO:mqtt_async:connecting wifi
lin-loop is running
INFO:mqtt_async:Connecting to ('192.168.1.21', 1883) id=b'0cb815cd8ff4' clean=1
INFO:mqtt_async:Connecting to ('192.168.1.21', 1883) id=b'0cb815cd8ff4' clean=0
Wifi connected
MQTT connected
set ha_autoconfig
publish energy_mix:gas
publish el_power_level:0
publish target_temp_water:0
publish target_temp_room:0
publish alive:OFF
publish heating_mode:off
publish operating_status:Off
publish current_temp_room:0
publish current_temp_water:0
publish alive:OFF
publish alive:OFF
publish alive:OFF

What could I check? I switched TX/RX from the ESP and also LIN/Ground. Does not seem to connect. Also did several resets on the CP+. No clue! Installed the latest unstable MicroPython and set up everything again... no dice!

What could I check next....? is it correct that the 12V-LED on the UART2LIN is lit?

**Comment by snipah** [comment]
![IMG_0781](https://user-images.githubusercontent.com/1154089/205148835-225be8f2-61aa-4ea4-b669-fa6be2187457.jpeg)
![IMG_0782](https://user-images.githubusercontent.com/1154089/205148853-7c81e8fa-7311-4e2b-bd5a-93aa199d1557.jpeg)
![IMG_0783](https://user-images.githubusercontent.com/1154089/205148878-36e01a46-0d49-42ae-83c3-d80ff92d9826.jpeg)
![IMG_0784](https://user-images.githubusercontent.com/1154089/205148895-67ee48c7-eae7-40f5-9d41-bf8ba561ee3b.jpeg)

**Comment by mc0110** [comment]
The Python-Version is okay, with a older version it throws a error. The MQTT-Connection is fine. 
Tx (17) has to be connected to RX(Lin-Interface). I think, this is wrong. You should use the LED-Debugger. In my car with my first tries (flying connections) I killed one LIN-UART and also one RPI pico (is running, but the tx-GPIO is quiet). After using the LED you see, if the Interface is sending anything or if it is dead.

**Comment by snipah** [comment]
Switched RX and TX.  No dice! What do you mean with grouding?

**Comment by snipah** [comment]
> Tx (17) has to be connected to RX(Lin-Interface). I think, this is wrong. 

The readme says differently..

**Comment by snipah** [comment]
Ordered a replacement LIN-UART and will send the old one back, as I assume it was not working correctly out of the box. Also ordered an MPU6050. Lets see how this can nicely be integrated into Home Assistant. BTW: Thanks for your efforts ;)

**Comment by snipah** [comment]
> I also ordered an MPU6050. If you're interested, there's a separate "issue" (#16) about MPU6050-related topics. 😉

...then lets work on something nice for home assistant. BTW: Ich bin "snipah" im Pösslforum.

**Comment by mc0110** [comment]
Hey snipah,
I am sorry that you were not successful.  But you are not the first to have problems with the LIN-TTL module.
I'll think about more diagnostics in the future.

**Comment by mc0110** [comment]
> Lets see how this can nicely be integrated into Home Assistant.

There is an example for a HA-integration from Sönke (skebber) in our docs

**Comment by mc0110** [comment]
Hey snipah, I would close this issue, if it is okay for you. Hopefully you see a connection with the new device - your comments will be welcome

**Comment by mc0110** [comment]
So you are right, on your pictures is clear to see the missing grounding - sorry that I didn't give you this hint. I'll try to pick this up in the docs

**Comment by mc0110** [comment]
![photo_2023-02-15 11 50 36](https://user-images.githubusercontent.com/10268240/219007521-d8005478-41de-4037-9b7e-c38b7e3975ab.jpeg)

Here is another very clear connection diagram from a successful installation

**Comment by tojo99** [comment]
Hi, I want ask you about project inetbox. Is that right connection? 
![image](https://github.com/mc0110/inetbox2mqtt/assets/46848945/bd1b38de-c947-457a-b621-613495aab381)
Between gnd and lin is still 1,5V (Uart Transceiver)? Thank you.

**Comment by mc0110** [comment]
of course
