### ISSUE TITLE
HA readme

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#23]
Hi Magnus!

Referring to your readme for the Home Assistant Lovelace card etc.:
> In the function, the hot water production is automatically switched off when the target temperature is reached.

Does the target temperature (eco/hot and boost) correspond to the temperatures explained in the Truma Combi manual 40/60°C?

I don't have the "E" Combi and therefore can only heat with gas. How do I have to adjust the 2 truma files (Lovelace card and yaml config) to remove or adjust some buttons? E.g. I don't need "Mix1", "Mix2" and "Elektrik", correct? Can I simply remove them from the card or do I have to adjust something else? Do I need the button "Gas" when I can only run gas? What happens if I remove it? Can I then not switch gas on? Sorry that I'm not sure about it and ask about this.

> In addition to the PRESETS, the heating can also be controlled very easily via automations using the climate.set_temperature service. In the lower part you can observe the status of the CPplus.
Does this regret to status like Abwesend, Komfort, Zuhause, Schlafen? Where are these status defined?

Thanks for your clarification! :-)

**Comment by mc0110** [comment]
Yes, the temperatures are corresponding! I have a user who uses the control and lives in his RV. He asked for the functionality. I found it practical and it can be easily turned off.

You can theoretically switch off the switching functionality, but you don't have to. It is sufficient to remove the one line from the Lovelance card.

Switching on / off works by changing the target temperature. When the target temperature is reached in the room, the heating is not switched off, only if this is explicitly switched off on the Lovelance card or if it is done on the CPplus. The status menu can be reached on the Lovelance card under the 3 dots (top right). Only preset temperatures can be called up with it. This can also be done with your own automations. A use-case would be, for example, to adjust the target temperature by opening the door with the appropriate sensors.
