### ISSUE TITLE
Wifi security & use: Encryption of Wifi password? Using WiFiManager lib?

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#3]
Hi Magnus!

Which kind of Wifi protection do you use in your code? I refer to this:
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/wifi-security.html

Besides, would you like considering encryption of the Wifi password before storing it on the ESP32? Currently, it is stored in plain text and is readable. Does this maybe help? https://forum.arduino.cc/t/esp32-secure-wifi-credentials/892762/4
Besides some code for it, you will also find a [note](https://www.esp32.com/viewtopic.php?f=19&t=22611) that
> The problem was solved:
> calling
> `WiFi.persistent(false);`
> before calling
> `WiFi.begin();`

As I don't have knowledge of coding with Python or MicroPython, I don't know if this is really helpful, but maybe (if this is of interest for you), it gives you some inspiration.

Maybe flash encryption is helpful, too: https://docs.espressif.com/projects/esp-idf/en/stable/esp32/security/flash-encryption.html#

> Make sure that you enable secure boot or write-protect encryption efuses so that the encryption configuration itself is secure (otherwise an attacker could flash a new firmware and simply dump the decrypted partition).
https://www.reddit.com/r/esp32/comments/nc2yio/most_secure_password_storage_strategy_for_esp32/

Alternatively to hard-coding the SSID & Wifi password in the code, you could consider using the WifiManager lib:
https://randomnerdtutorials.com/esp32-useful-wi-fi-functions-arduino/
https://www.youtube.com/watch?v=VnfX9YJbaU8

Or this project: https://github.com/tzapu/WiFiManager

Please accept my apologies if this is way out of scope. 😊

**Comment by mc0110** [comment]
This is an interesting problem. I used to have all my ESP modules equipped with the tzapu WifiManager. Here, if I remember correctly, the credentials are stored in the chip - but I don't think they are encrypted either. With my solution, no credentials are flashed, but they are stored in readable form on the chip. That is a security gap - I agree with you.
I have now looked through all the "WifiManager for uPython" projects and tried them. But it's all very disappointing. I'll have to see how I can best solve this. But thanks in any case for the hint. I'll leave the issue open for now.

**Comment by mc0110** [comment]
For your info, I finalized yesterday the crypto-logic. But it isn't in the repro up to now

**Comment by mc0110** [comment]
I'm not sure that I have seen this repo in my research for Wi-Fi manager. But there is another approach also interesting - to use the mqtt server also for file-handling and it's.

**Comment by mc0110** [comment]
So I'll test it and then we can discuss the best way

**Comment by mc0110** [comment]
I have just published the corresponding routines in [crypt_keys](https://github.com/mc0110/crypto_keys), which will be used in the next version of inetbox2mqtt and which will only allow the credentials to remain encrypted on the chip. With that, I think the issue can be closed.
