### ISSUE TITLE
How to place truma.yaml separately in Home Assistant?

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#31]
Hi Magnus,

I needed to reinstall HA on my Pi4 and placed `truma.yaml` separately in the `/config` folder (besides `configuration.yaml`). Before, I had your `truma.yaml` code directly inserted in `configuration.yaml` but that got too large in the meantime, hence placing `truma.yaml` separately and referring to it from inside `configuration.yaml` seemed to be good to me. Following [this guidance on splitting the HA onfiguration](https://www.home-assistant.io/docs/configuration/splitting_configuration/), I thought it works like this:

config/configuration.yaml
```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Truma inetbox2mqtt
#
truma: !include truma.yaml
```

I can save the `configuration.yaml` like this, but when I use the HA check of that config, it tells me:
> Integration error: truma - Integration 'truma' not found.

I have no idea what I'm missing now. Can you please provide me with a hint? How have you set this up in your HA config? Thank you so much for your help!👍

**Comment by mc0110** [comment]
The truma.yaml is a package in the HA logic. 
Please note this description: [packages](https://www.home-assistant.io/docs/configuration/packages/)

**Comment by mc0110** [comment]
You can find a German description under the link [Schleeh](https://schleeh.de/2023/02/17/inet-box-fuer-wohnmobilheizung-selbst-bauen/). Hannes rebuilt it just like you and of course found all the trapdoors. This is the basis for his instructions. 

If you flash the new version onto your ESP32, there will be no problems. This has already worked for many people without any problems and you have already bypassed the hurdles with the LIN connection.
