### ISSUE TITLE
Truma switches automatically on after HA restart

### ISSUE THREAD

**Issue by CzarofAK** [mc0110/inetbox2mqtt#38]
My HA is switching on the Room Heater after rebooting. I have also troubles to keep the truma switched off. Somehow it starts automatically!

**Comment by CzarofAK** [comment]
![Screenshot_20230328-213639](https://user-images.githubusercontent.com/64549444/228348309-a3f2230e-e2c7-410c-92af-f0b25f2ee67c.png)

**Comment by mc0110** [comment]
I need more info about our setup! The HA automation is correct function only with Celsius degrees

**Comment by CzarofAK** [comment]
Yes, of course, everything you need.
i have copied your truma.ii and yaml.
the only thing changed is, the min temp for a test (to switch it off via target room temperature setting.
i can switch it off on the truma panel.

**Comment by mc0110** [comment]
Sorry, I don't understand the problem. 

If I understand correctly, you are using my ESP module and can also control the Truma via MQTT. The HA scripts have been tested many times and run perfectly in many installations. If you have changed something, you have probably made a mistake.

**Comment by CzarofAK** [comment]
I use your code straight out the box. I have made changes to investigate the fault.

It seems like that the home assistant cant either send the data correctly to the esp or the esp cant send the data to the bus.

**Comment by mc0110** [comment]
I don't understand what you mean?

**Comment by mc0110** [comment]
The best thing to do is to reinstall ESP and HA Yaml.
