### ISSUE TITLE
"Update Repo"-related questions

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#40]
Hi Magnus,

Is it intented that an "Update Repo" loads also `duocontrol.py` and `spiritlevel.py` even if these 2 modules were not enabled in the previous version?

E.g., my ESP32 was running RelNo:1.5.a and both modules disabled (i.e. not selected during the setup and not enabled later either). Then I did an "Update Repo" and saw that these 2 modules were loaded. Is this needed in case the user wants to enable them and to ensure that then they are up-to-date?

BTW, after the update, the footer still shows the initial version:
> MIT (c) Dr. Magnus Christ (2022) RelNo:1.5.a

I assume that this info is just not updated but I am a bit unsure. Maybe the update was not fully successful? How could I check?

Finally, does the "Update Repo" function always update to your latest Repo main? How about breaking changes that could happen? Would it then be possible to update to some "in-between-version" to keep things running?

Thanks and my best regards
7wells

**Comment by mc0110** [comment]
To use the 2.x versions, you must first flash the ESP32 again. I have also explained this in the readme, because due to the small RAM memory, part of the code is in the flash memory.
