### ISSUE TITLE
AP mode

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#41]
Dear Magnus,

Is my understanding correct that if inetbox2mqtt falls back to AP mode, which is open Wifi, anybody could connect, go to the WebGUI, click on "Status" and see the entered Wifi credentials? Would you consider this a safety concern?

Sorry if I am completely wrong and have unnecessarily stirred the water.

Wishing you and all other kind people peaceful Easter! ☮️🥚🐔🍀

**Comment by mc0110** [comment]
So if you were not in the "experimental phase", your ESP32 would be in "normal mode" and no one could see your credentials. 

Yes, I put the data in the status on purpose. There were the problems with the credentials for most newbies to get the system up and running.
