### ISSUE TITLE
No AP after flashing ESP32

### ISSUE THREAD

**Issue by Morris124** [mc0110/inetbox2mqtt#48]
Hello Magnus,

thank you for creating this awesome project. Unfortunately I am not able to see an AP after I flashed my ESP32. 

To flash the device I used esptool and my output was:

> esptool.py write_flash 0 /Users/morris124/Downloads/flash_esp32_inetbox2mqtt_v264_4M.bin.zip
esptool.py v4.5.1
Found 3 serial ports
Serial port /dev/cu.usbserial-0001
Connecting....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting......
Detecting chip type... ESP32
Chip is ESP32-D0WD-V3 (revision v3.0)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 94:b5:55:fa:1e:b4
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Flash will be erased from 0x00000000 to 0x0012ffff...
Compressed 1243380 bytes to 1233489...
Wrote 1243380 bytes (1233489 compressed) at 0x00000000 in 108.9 seconds (effective 91.4 kbit/s)...
Hash of data verified.
Leaving...
Hard resetting via RTS pin...`

So I assumed it was succesfully written on my ESP32.
The red LED is constantly flashing super fast.

To troubleshoot the issues I already tried a diffrent ESP32 with no success. I hope I'm not missing something obvious. 

I would be happy for any advice.

**Comment by gmanic** [comment]
Don't flash the .zip file but the unzipped .bin file.
IIRC fast flashing says 'no bootloader', which of course the zip does not provide.
