### ISSUE TITLE
No switch to OS-Mode from Terminal

### ISSUE THREAD

**Issue by Stiles96** [mc0110/inetbox2mqtt#49]
At the boot I get the message: "INFO:__main__:Normal mode activated - for chance to OS-mode type in terminal:"

I can't type anything in the terminal to change to OS-Mode or the system don't switch. I can't use the MQTT Interface because this interface makes trouble and I have to switch my credentials.

**Comment by mc0110** [comment]
Which hw do you use?

**Comment by Stiles96** [comment]
Hardware is ESP32

**Comment by mc0110** [comment]
Ok, then have a new flash, pls
