### ISSUE TITLE
Change config later?

### ISSUE THREAD

**Issue by el-Presi** [mc0110/inetbox2mqtt#50]
Hi there, maybe thats wrong here, but..: how do I open up the AP again to maybe change the Wifi or MQTT config?

**Comment by el-Presi** [comment]
or lets ask otherwise: I did not get the point yet to change the mode of the OS to normal, only that I cannot access the config page anymore and that the AP is closed ? Is there a way to open the AP up again? :)

**Comment by mc0110** [comment]
After entering the credentials, the WiFi and MQTT connection is established after a reboot. You can then test these. Only when everything works does one switch to NORMAL mode. The way back is via an MQTT command (see README). Otherwise, you have to go through the installation process again.
