### ISSUE TITLE
Ventilation Mode

### ISSUE THREAD

**Issue by Stiles96** [mc0110/inetbox2mqtt#53]
System:
ESP32, Truma CP Plus, Truma Combi 4

At the Truma CP Plus Panel I can select the Ventilation Mode. To turn it on, I have to select mode "vent" and can choose the speed by 1 - 10.
It's the same ventilation, wich is use by the heating mode. By heating the ventilation only have eco and fast.

The mqtt has some aircon values to set the system to vent, but not the speed. I don't know, if it works.

I also have some pictures to show that on the CP Plus:
 
![20231007_121058](https://github.com/mc0110/inetbox2mqtt/assets/51234422/7ee6587b-36a1-4850-ac24-0562685dbada)
![20231007_121112](https://github.com/mc0110/inetbox2mqtt/assets/51234422/76c1f2c7-bb15-449d-9a4a-8418b667f0d7)
![20231007_121120](https://github.com/mc0110/inetbox2mqtt/assets/51234422/990f832e-f8d6-4389-b4e4-203f849f4194)

**Comment by mc0110** [comment]
Sorry, You couldn't control the truma vent mode with my solution. If you use a aventa aircon, it is possible to set the aircon vent-mode

**Comment by mc0110** [comment]
This isn't a bug
