### ISSUE TITLE
MemoryError: memory allocation failed, allocating 776 bytes

### ISSUE THREAD

**Issue by lembnau** [mc0110/inetbox2mqtt#55]
Hi,

nach ein paar Stunden bekomme ich im seriellen Monitor (Putty) diesen Fehler und es findet keine Kommunication mehr statt

**Comment by mc0110** [comment]
which device?
which mode (os-mode or standard)?
what do you mean with "no communication" -> http, mqtt, lin

**Comment by mc0110** [comment]
Normally, when you are in http-communication, you see this more often (unfortunately, the chips don't have enough RAM and micropython unfortunately packs the "normal" code into the RAM area

**Comment by mc0110** [comment]
The error is not really a software error. A memory error is triggered when you try to fetch the subscription. This is not possible in the versions that is in the repo. Without a complete log and details about the version and also the hardware you are using, I can’t help.

**Comment by Carstens-Paulette** [comment]
IT seams that I have the same issue.
I will try to get some detailed logs about it.
In case, the ESP is simply running out of memory, how to deal with it? One approach would be to switch off the controller by the MQTT receiver. Im my case the VenusOS, which fortunatly have relays. Or is it possible to reset the ESP on low memory?

Follow up to be expected.

kind regards

Carsten O.

**Comment by mc0110** [comment]
Hi Carsten,

that is very unlikely. Inetbox2mqtt is now very often used and has been tested for many months. Are you using the LAN connection and the WOMOLIN hardware? I really need the logs and the point at which the ESP32 exits. I myself run the code on an RPI, which has a larger RAM area. Jan has used the newer ESP32s, but the memory is switched via a mapping, which the micropython does not support.
