### ISSUE TITLE
after switching the OS mode - how can I switch back to the web interface?

### ISSUE THREAD

**Issue by robgreiner** [mc0110/inetbox2mqtt#61]
Hello, I would like to use your solution on a womolin Controller 2.1. So far, flashing the ESP32 has worked perfectly. When I trigger the switch OS via the web client in AP mode, the box connects via WLAN - also ok. But as described, the web client is then no longer accessible. 

My question: How can I switch back to AP mode and the web client?

**Comment by mc0110** [comment]
See the closed issue "https://github.com/mc0110/inetbox2mqtt/issues/32"

As described in the readme, there are two ways to switch back to OS mode.

Option - with a terminal connection
Normal mode activated - for chance to OS-mode type in terminal:

import os
os.remove('run_mode.dat')

Option - with an MQTT connection
send topic 'service/truma/set/os_run' with a payload '1'

**Comment by robgreiner** [comment]
thanks!
