### ISSUE TITLE
Switching modes

### ISSUE THREAD

**Issue by felixreher** [mc0110/inetbox2mqtt#63]
Hi Magnus, maybe I just missed this - but is there a way to switch from normal mode back to OS mode or does the ESP have to be re-flashed? It seems my broker isn't getting any messages, so I would like to double check my credentials.

**Comment by mc0110** [comment]
Hi Felix, there are several ways to return from normal mode to OS mode. However, in your case I recommend the ESP re-flash as the easiest way. In OS mode, you have the explicit option of testing the broker connection. Only when this is stable should you switch to normal mode.
