### ISSUE TITLE
Truma Aventa Compact plus

### ISSUE THREAD

**Issue by aloisbrau** [mc0110/inetbox2mqtt#67]
Hallo. Schreibe auf Deutsch, da ich nicht perfekt in Englisch bin. Könnte es aber auch mit Mühe in Englisch formulieren!
Die Anbindung über mqtt in Home Assistant funktioniert bei der Truma Heizung sehr gut.
Leider habe ich keine Truma Aventa Comfort sondern die Aventa Compact plus.
Diese wird leider nicht angesteuert.
Könnte es sein dass hierfür andere ID in der Aventa.yaml notwendig sind?
Vielleicht gibt es eine Möglichkeit über NodeRed?
Finde hierzu leider nichts, möchte aber auch bei mqtt bleiben!

Danke
Alois

**Comment by mc0110** [comment]
Hallo Alois,
freut mich, dass die Truma geht!
Wenn die Aventa Compact plus nicht auf die Codes reagiert, dann ist das nicht auf der YAML-Ebene änderbar. Es tut mir dann leid, aber da gibt es keine Chancen einer Steuerung.
Das ist unabhängig von Node-Red / MQTT, hierbei geht es um die LIN-Kommunikationsebene.
Beste Grüße
Magnus

For all the english speaking members:
I'm pleased that the Truma is working!
If the Aventa Compact plus does not respond to the codes, then this cannot be changed at the YAML level. I'm sorry then, but there's no chance.
This is independent of Node-Red / MQTT, this is about the LIN communication level.

**Comment by aloisbrau** [comment]
Hallo! Nach eingehenden Tests und Auslesen von Daten aus unterschiedlichen Konstellationen bin ich einen Schritt weiter.
Mit esphome truma-inetbox von Fabian Schmidt kommen zumindest Daten der inetbox von der Aventa Compact Plus.
Passt alles zwar noch nicht, aber wenigstens habe ich jetzt eine Datenverbindung über Lin-Bus.
Dort hat jemand auch eine Saphir Klima eingebunden. Scheint doch möglich zu sein. Ich bleibe dran!!!!

**Comment by aloisbrau** [comment]
Nochmal ich!!!

Nach vielen Versuchen und Auslesen der Daten ist es mir nun gelungen die Truma Aventa Compact plus zu steuern.
Es lag einzig und allein daran, dass ich einen ESP 32 in Betrieb hatte. Habe nun alles auf PICO 2 W umgebaut und siehe da:
es funktioniert. Manchmal kann das Leben ganz einfach sein.
Falls jemand auch diese Probleme hat, sollte er auch den PICO 2 W benutzen.

Vielen DANK für die Hilfe an Magnus_



It's me again!!!

After many attempts and data retrievals, I've finally managed to control the Truma Aventa Compact Plus.

The problem was solely due to the fact that I was using an ESP32. I've now switched everything to a PICO2W and lo and behold:

it works! Sometimes life can be so simple.

If anyone else is experiencing these problems, they should also use the PICO2W.



Many thanks to Magnus for his help._

**Comment by mc0110** [comment]
Hallo Alois,
super, dass es jetzt klappt. Hast Du irgendeine Idee, warum das so ist. Normalerweise sind die Softwareversionen auf beiden Geräten identisch. Meine Tests habe ich immer mit beiden Hw-Konfigurationen gemacht.
Ich könnte mir nur vorstellen, dass die HW-Details (config-Datei) nicht richtig gezogen wurden.
Beste Grüße
Magnus

P.S. Kannst Du mir noch den Softwarestand der INetBox sagen, bitte. Der kommt bei der INIT-Abfrage

**Comment by aloisbrau** [comment]
Hallo.Danke für die Mail.Ich habe schon viele Versuche mit verschiedenen ESP32 mit jeweils neuem Download der von Dir zur Verfügung gestellten Software probiert. Die config habe ich auch ausgelesen und keine Fehler festgestellt.Nachdem ich nunmehr auf den Pico 2 w umgestiegen bin, läuft alles ohne Probleme.Die ESP32 werde ich anders verwenden. Mit einem lese ich die Daten meiner LifePo4 über BLE in HA aus. Funktioniert auch sehr gut. Die ESP32 sind also auch o.k.Danke nochmals für Deine tolle Arbeit.Zu Deiner Frage:Ich habe die aktuelle micropython Version geflasht 1.27.0Der Index der Truma sind:C4.03.00         CpPlus H5.00.00         Truma 6A1.00.02          Truma Compact PlusT23.70.0           inetboxHoffe das hilft etwas bei Problemen von anderen Campern.Hätte aber auch noch eine Frage: Kann ich die interne LED des Pico mit GPIO 25 ansteuern, wenn ich Deine tools.py - rp2 bei mqtt_led von 14 auf 25 umstellen? Wahrscheinlich aber nicht so einfach???Liebe Grüße Alois--Gesendet mit der GMX Mail AppAm 09.01.26, 09:40 schrieb "Dr. Magnus Christ" ***@***.***>:
mc0110 left a comment (mc0110/inetbox2mqtt#67)
Hallo Alois,
super, dass es jetzt klappt. Hast Du irgendeine Idee, warum das so ist. Normalerweise sind die Softwareversionen auf beiden Geräten identisch. Meine Tests habe ich immer mit beiden Hw-Konfigurationen gemacht.
Ich könnte mir nur vorstellen, dass die HW-Details (config-Datei) nicht richtig gezogen wurden.
Beste Grüße
Magnus
P.S. Kannst Du mir noch den Softwarestand der INetBox sagen, bitte. Der kommt bei der INIT-Abfrage

**Comment by mc0110** [comment]
Hi, danke für die schnelle Antwort und die Versionsstände. Die Änderung des GPIO von 14 auf 25 sollte funktionieren. Ich bin mir nur nicht sicher, ob die interne LED "frei" ist, also wenn Du die so ansprechen kannst, dann geht es auch über die Software.

Bytheway: Bei mir im Auto habe ich auch einen PICO seit 2,5 Jahren im Einsatz. 
Gute Fahrt wünsche ich Euch!!
