### ISSUE TITLE
Information on steps for going back to original INetBox

### ISSUE THREAD

**Issue by dannycjones** [mc0110/inetbox2mqtt#73]
Hey, thank you for sharing this project.

I was searching for something like this, and hoping to learn what the process would be like to install and uninstall/rollback if I needed to. I was looking for two pieces of information. I believe I actually have answers for the both of these, but I wanted to confirm with you (and perhaps we can add them to the README).

>**Why must I disconnect the original INetBox?**
>
>I assume this is because on LIN you can only have one commander and many responders (prev. master and slaves), with the INetBox or this project acting as the one commander.
>
>**What are the steps to remove this project and go back to using the INetBox?**
>
>I assume it's a case of wiring back up the INetBox and running a reset on the control panel.

I haven't tried this project out yet, so I am very much speculating here 😄

**Comment by mc0110** [comment]
1st question: Your answer is the correct assumption. The INetBox reacts to the CPplus commands. If there were 2 in the system, there would be problems
2nd question: Your assumption is also correct. You can reactivate your Inetbox at any time with a RESET, but believe me, you don't want to once you have enjoyed the benefits.
