### ISSUE TITLE
current_temp_water does not change

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#8]
Hi Magnus!

Now that my setup seems to work nicely with your code on my ESP32 and my Truma Combi 4, I realise that `current_temp_water` does not change; it stays 12.0 °C all the time, whereas `current_temp_room` changes as expected - see graphs from 2 different tools (IoT MQTT Panel Android app above; HA below):

![Screenshot_20221109_071307.jpg](https://user-images.githubusercontent.com/65889763/200753431-ac23798e-a330-47d0-b56c-fa321b05a591.jpg)

![Screenshot_20221109_071546.jpg](https://user-images.githubusercontent.com/65889763/200753819-b675c384-3fab-4874-a1dc-378b642eba93.jpg)

How can I find out the reason for this? Attaching the ESP32 to my laptop and reading the Thonny shell while changing water temperature on the CP+, or doing something else?

In previous nights (and with Daniel's code on the RPi4), the water temperature display changed, too.

I find it remarkable that the room temperature in the graph above (IoT app) shows changes more pronounced than the other. Is this because of different values or just less accurate on the other?

**Comment by mc0110** [comment]
But you have the hot water off? Then you only see that water acts like a buffer against temperature fluctuations due to its significantly higher heat capacity. Yes, and it has nothing to do with the code on the ESP32 but only with the climate in your environment.
HA scales the graphs automatically, hence the better resolution if you leave out the temperature jump in the data.

**Comment by mc0110** [comment]
At the moment my water temperature is also 12degree ;-)

![grafik](https://user-images.githubusercontent.com/10268240/200771201-c99ff4dd-ba49-42d2-b2b7-c8ee72ff68dc.png)

**Comment by mc0110** [comment]
![grafik](https://user-images.githubusercontent.com/10268240/200771632-c27abcc6-87d6-4440-b95c-3b9f7d187836.png)

And for comparison - measured with several thermometers in the vehicle, here is the room temperature of the last day. The curve looks similar.
