### ISSUE TITLE
Reading of raw values?

### ISSUE THREAD

**Issue by 7wells** [mc0110/inetbox2mqtt#9]
Hi Magnus!

Is there a way to read **raw** values from the ESP32 with your code, or how could I try to figure out the meaning of data that have not yet been identified? E.g., the fan that can be controlled via the CP+ when the air heating is off; it then serves simply as a fan. Maybe you also have some other data of interest?

**Comment by mc0110** [comment]
You can take Daniel's code as a basis, all the parts are in there! What exactly do you want to analyse?

**Comment by mc0110** [comment]
I think, we can close this issue! Ok for you?
